apiVersion: v1
kind: Namespace
metadata:
  name: example
---
apiVersion: stable.dwk/v1
kind: DummySite
metadata:
  name: example
  namespace: example
spec:
  website_url: 'https://example.com/'
  image: ruuskhis/dummysite:1.0.0
---
apiVersion: stable.dwk/v1
kind: DummySite
metadata:
  name: dwk
spec:
  website_url: 'https://devopswithkubernetes.com/'
  image: ruuskhis/dummysite:1.0.0
