apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-broadcaster-dep
spec:
  replicas: 6
  selector:
    matchLabels:
      app: todo-broadcaster
  template:
    metadata:
      labels:
        app: todo-broadcaster
    spec:
      containers:
        - name: todo-broadcaster
          image: TODO_BROADCASTER_IMAGE
          imagePullPolicy: Always
          env:
            - name: NATS_URL
              value: nats://my-nats:4222
          envFrom:
            - secretRef:
                name: secrets
