apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-broadcaster
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: todo-broadcaster
    spec:
      containers:
        - env:
            - name: NATS_URL
              value: nats://my-nats:4222
          envFrom:
            - secretRef:
                name: secrets
          image: TODO_BROADCASTER_IMAGE
          imagePullPolicy: Always
          name: todo-broadcaster
