apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: todo-backend
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: secrets
            - configMapRef:
                name: pg-configmap
          image: TODO_BACKEND_IMAGE
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3001
            initialDelaySeconds: 20
            periodSeconds: 5
          name: todo-backend
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              cpu: 80m
              memory: 150Mi
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: todo
      volumes:
        - name: todo
          persistentVolumeClaim:
            claimName: todo-claim
