apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      volumes:
        - name: todo
          persistentVolumeClaim:
            claimName: todo-claim
      containers:
        - name: todo-backend
          image: TODO_BACKEND_IMAGE
          imagePullPolicy: Always
          volumeMounts:
            - name: todo
              mountPath: /usr/src/app/files
          envFrom:
            - secretRef:
                name: pg-password
            - configMapRef:
                name: pg-configmap
          resources:
            limits:
              cpu: '80m'
              memory: '150Mi'
