apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: todo-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
