apiVersion: v1
kind: Secret
metadata:
    namespace: project
    name: secrets
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:8VCT7Nh09TIOJznp,iv:gYP6bWMaF2AGl3o6t7vRX+qHtqF1lvSHxSz7SVpG9qY=,tag:qy//msz7kaSBY2MfnaHJeg==,type:str]
    TELEGRAM_TOKEN: ENC[AES256_GCM,data:cySBc4xxYny+HPPKqKDmZJoVbLOoKnwKkLZAFaIAdLGi/KuG8byb5xcN5cxcMg==,iv:YA2HklryeC3Ez87S+WcBwMaMx35zzNysz6zXdjLwp8g=,tag:wROlhJ2rd2E19KAj8b7mDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lxfszc27suwntwmc9v2x5l4cyxa4umg7pz4mena35grcv3m5npsskt88cc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWThybGYreTVKeUZxUHR1
            Z0hEaHUzRjVMK0tzRURmK3laSVJzSzFPSnhvCmhkdlNLNEVqS1ZTNE5BblRNWkIy
            Z01nQWh3aEFoQi91Wmc4YWV6RnlzR2sKLS0tIElJU09YUCs3bExOZFlGaW5mck5t
            L0pQYVd0WDl2WU0vVXFhOXZhd3NjYjQKlzjP41nh0i5g1Kswm1CuqIYUWXw9WiPG
            S4rUIBr9kCLQrz1t9JvpEW9bD46ZG5q/U0dnsJcScJCMiJqMxBnNMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-02T06:48:29Z"
    mac: ENC[AES256_GCM,data:lYYHfPxWoLRvOSKpV39ioQjZmtQsZYQhDfBTRJ0qg3zE2exByGXIHlKYAZN6TAwFm7Gu2rn5Fpuy4IzyU/ep5NXHAnl/8b1LaDYYTbSA1+XIsGrm2NdyLkS4yShTbKwkTalNjYBUl8k0Dw2+ndW3hpAVXdaKgBslW+rhe/ewn3E=,iv:sEoRMQS8mBkryAHX+Td1XMqDfJKIhjlKtF5zSDDa1mw=,tag:Mm8AVLOVyjXIeELvtQQsJQ==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.7.3
