apiVersion: v1
kind: Secret
metadata:
    namespace: project
    name: secrets
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:kaKM7Hhj1CLOWj+l,iv:1h2RiS7d1YWEoFe/P0qI7YFM+E5t8T5P2QTFIsSsh0g=,tag:xt4VnI85MN8JpoCuyoGSyg==,type:str]
    TELEGRAM_TOKEN: ENC[AES256_GCM,data:sfemGk+PuGL9flgmECz9nFW5sL1IDTg2d5pZhlyp1wvZ02tKH41Zi/i3QQp5z5MnVGAApJLXM1RFh+1W7cw4IQ==,iv:E0neGpQoD8DBILwfSit+l1jM2CelfBOHXJkVCDcivjc=,tag:kl8J5Z6rdMEidR0ArYqTdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lxfszc27suwntwmc9v2x5l4cyxa4umg7pz4mena35grcv3m5npsskt88cc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QVY1NDRaMmpCeXR4TDcz
            bGZZdkxvaXBERUZPY2R6Q09HWWEvQThoN3d3CklkdlNlSG9UbTJYTVlXNkNaaXYx
            K1NXOHJWRGYvK21qTTRuc2VoQnE1MkUKLS0tICs5QzIzOHJtYjdad2orK3dVSmg4
            Q01kdE1aSUU3blgxMkR3QnZleGdaWjgKqhRErjv5yKqrngAMy23UNbYtpUahWYba
            Fv4oZ5rBu4/spKCHcJHD7Xy/AJFJiRc0ntz5X0tG+xBtC0Z/6aksWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-30T08:53:52Z"
    mac: ENC[AES256_GCM,data:SFdo4gFEycrH2iGAl7F2+JZIeTcj2PvniGs5qlDTnjqqGa0PxBy7DcbxUwYhmJxI79IM9+7/Hv9OLE15pOenOsVC0l+D637QC/yipakCfUn/W6XvEJJSAMq5Iz8UU0ssEpf45hhm6VYwob/j+Q9hMlET0Nj9UWIBD3MHca0uoQQ=,iv:LT0HzbI3C6SwkmpGrmlo5VbElarqdH2ykcrLYf2Yi4s=,tag:TPk7QBRQNdy0iY8KRf1Ogw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
