apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: log-claim
        - name: dotenv-config-map
          configMap:
            name: log-dotenv
      containers:
        - name: log-output-writer
          image: ruuskhis/log-output-writer:latest
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
        - name: log-output-reader
          image: ruuskhis/log-output-reader:latest
          imagePullPolicy: Always
          env:
            - name: PINGPONG_URL
              value: 'http://ping-pong-svc:2346'
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
            - name: dotenv-config-map
              mountPath: /usr/src/app/config
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000
          resources:
            limits:
              cpu: '80m'
              memory: '150Mi'
