apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: exercises
  name: log-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
