apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        # - name: shared-logs
        #   persistentVolumeClaim:
        #     claimName: log-claim
        - name: pings
          emptyDir: {}
      containers:
        - name: ping-pong
          image: ruuskhis/ping-pong:latest
          imagePullPolicy: Always
          volumeMounts:
          - name: pings
            mountPath: /usr/src/app/files