apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: log-claim
      containers:
        - name: ping-pong
          image: ruuskhis/ping-pong:latest
          volumeMounts:
          - name: shared-logs
            mountPath: /usr/src/app/files