apiVersion: v1
kind: Secret
metadata:
    namespace: exercises
    name: pg-password
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:OrKUiGIAlW4YPGCF,iv:tZz/oL/tnihjJL2RGECZCIFVJ6m4UqHy4ufr1gBr0KA=,tag:lH+ujEnXYHnM6qOzivvHBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lxfszc27suwntwmc9v2x5l4cyxa4umg7pz4mena35grcv3m5npsskt88cc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCU3NKOEZBQ0xIRVBwWXZq
            TTRVS2NzRy8zaDluNmtDSWp3NmtLMkNtakVNCndxekVFUjBrdXN4MDBUZWNkR3ZC
            eUtUWUlIYkgrVXY3MDMxc1B1dG9obEkKLS0tIFkvL3ZnNEg2RndSaEh2QlNNSmd6
            VkNYdzlPTU12L2tOMmxpOUhSQ1B1aVEKS/USyzWiSWkmcOb19Q3GGfGROO+l0xRS
            VU3b3nM+b5lNiZbCcYSTz8Cshq44oAKwpsfQ8ciH8hkbTKXOf7PBUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-01T17:06:21Z"
    mac: ENC[AES256_GCM,data:AfjgEr2fKvy1gwPGuS4nC7RZlEODM3m/WQFS8Z0VW1BVU3+u1E0nl0+azmoFRv/MCuGQa15x49iCOF/J7rIF7csrXsARNhp6oRYtY6giw6vcZRqUk5DFhE6zKk80atmutyO3p3+dBFMbe86LSmnwx9x42KjSeWyIBHuFpC2b9ZQ=,iv:aZ1iCqHv4KVkKtVuLyoknu+tRnwGN4jzMQm1tKDFBNU=,tag:dd5UKRJ5Gcu+7JvNI6OVkA==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.7.3
