apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: ping-pong-svc
spec:
  #type: ClusterIP
  type: LoadBalancer
  selector:
    app: ping-pong # This is the app as declared in the deployment.
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
