apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-svc
spec:
  type: ClusterIP
  selector:
    app: todo-frontend # This is the app as declared in the deployment.
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 80