apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: todo-frontend-svc
spec:
  type: NodePort
  selector:
    app: todo-frontend
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 80
