apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily
  namespace: project
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            linkerd.io/inject: enabled
        spec:
          containers:
            - env:
                - name: URL
                  value: http://todo-backend-svc:2346/api/todos
              image: ruuskhis/todo-daily:1.0
              name: daily
              resources:
                limits:
                  cpu: 30m
                  memory: 30Mi
          restartPolicy: OnFailure
  schedule: 0 0 * * *
