name: Release todo-app
on:
  push:
    branches:
      - main
    paths:
      - 'todo-app/**'
      - '.github/workflows/deploy.yaml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push backend
        uses: docker/build-push-action@v2
        with:
          context: todo-app/backend
          push: true
          tags: ruuskhis/todo-backend:${{ github.sha }}

      - name: Build and Push frontend
        uses: docker/build-push-action@v2
        with:
          context: todo-app/frontend
          push: true
          tags: ruuskhis/todo-frontend:${{ github.sha }}

      - name: Build and Push daily
        uses: docker/build-push-action@v2
        with:
          context: todo-app/daily
          push: true
          tags: ruuskhis/todo-daily:${{ github.sha }}

      - name: Build and Push broadcaster
        uses: docker/build-push-action@v2
        with:
          context: todo-app/broadcaster
          push: true
          tags: ruuskhis/todo-broadcaster:${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      # Set up kustomize
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1

      # Update yamls
      - name: Update yamls
        working-directory: todo-app
        run: |-
          kustomize edit set image TODO_FRONTEND_IMAGE=ruuskhis/todo-frontend:${{ github.sha }}
          kustomize edit set image TODO_BACKEND_IMAGE=ruuskhis/todo-backend:${{ github.sha }}
          kustomize edit set image TODO_DAILY_IMAGE=ruuskhis/todo-daily:${{ github.sha }}
          kustomize edit set image TODO_BROADCASTER_IMAGE=ruuskhis/todo-broadcaster:${{ github.sha }}

      # Commit and push
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'todo-app/kustomization.yaml'
          message: New version release for todo-app ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
